package pt.ubi.di.connection;


import pt.ubi.di.Model.Validations;
import pt.ubi.di.security.model.SecurityDH;
import pt.ubi.di.security.model.SecurityMP;
import pt.ubi.di.security.model.SecurityUtil;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Objects;


public class Server_Lite {
    private ServerSocket serverSocket;
    private Socket socket;
    private ObjectOutputStream outputStream;
    private ObjectInputStream inputStream;

    /**
     * Constructor to create a serve_lite,
     * responsible to create a new connection private between a server_lite and a client_lite
     * @param port the port of the connection
     */
    public Server_Lite(int port) {
        try {
            serverSocket = new ServerSocket(port);
            System.out.println("Another server created!");
            socket = serverSocket.accept();
            try {
                System.out.println("Socket accepted");
                int index = -1;
                outputStream = new ObjectOutputStream(socket.getOutputStream());
                inputStream = new ObjectInputStream(socket.getInputStream());
                while (true) {
                    System.out.print("Private>");
                    String[] options = Objects.requireNonNull(Validations.readString()).split(" ");
                    switch (options[0]) {
                        case "-dh":
                            index = SecurityUtil.lookOptions(options,"help");
                            if(index!=-1)
                                SecurityDH.help();
                            else {
                                outputStream.writeObject("dh");
                                byte[] keyDH = SecurityDH.startExchange(outputStream,inputStream, options);
                                System.out.println("Key generated by Diffie-Hellman:\n" + SecurityUtil.byteArrayToHex(keyDH));
                            }
                            break;
                        case "-mkp":
                            index = SecurityUtil.lookOptions(options,"help");
                            if(index!=-1)
                                SecurityMP.help();
                            else {
                                outputStream.writeObject("mkp");
                                byte[] keyMP = SecurityMP.startExchange(outputStream, inputStream, options);
                                System.out.println("Key generated by Diffie-Hellman:\n" + SecurityUtil.byteArrayToHex(keyMP));
                            }
                            break;
                        case "-sk":
                            outputStream.writeObject("sk");
                            //DH implementation
                            /*
                            byte[] sessionKey = SecurityUtil.generateNumber(Integer.parseInt(options[1]));
                            byte[] cipherKey =  SecurityDH.startExchange(outputStream,inputStream,options).toByteArray();
                            System.out.println("key:"+SecurityUtil.byteArrayToHex(cipherKey)+" SIZE: "+cipherKey.length);
                            byte[] cipher = SecurityUtil.encryptSecurity(sessionKey,cipherKey);
                            outputStream.writeObject(cipher);
                            System.out.println("SESSION KEY: "+SecurityUtil.byteArrayToHex(sessionKey));*/

                            /*byte[] sessionKey = SecurityUtil.generateNumber(Integer.parseInt(options[1]));
                            byte[] cipherKey = SecurityMP.startExchange(outputStream, inputStream);
                            byte[] cipher = SecurityUtil.encryptSecurity(sessionKey, cipherKey);
                            byte[] hmac = SecurityUtil.hmac(sessionKey);

                            outputStream.writeObject(cipher);
                            outputStream.writeObject(hmac);
                            System.out.println("SESSION KEY: "+SecurityUtil.byteArrayToHex(sessionKey));*/

                            break;
                        case "-help":
                            System.out.println(
                                    "Commands =============================\n" +
                                            "-dh , Diffie-Hellman Key-agreement protocol\n" +
                                            "-mkp , Merkle Puzzle Key-agreement protocol\n" +
                                            "-sk , share a session key by using a KAP\n" +
                                            "Type -\033[3moption\033[0m help, for more information regarding each option\n" +
                                            "================================================\n"
                            );
                            break;
                        case "exit":
                            outputStream.writeObject("exit");
                            socket.close();
                        default:
                            System.out.println("The command \"" + options[0] + "\" not found!\nTry Again or use \"-help\"");
                            break;
                    }
                }
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        } catch (IOException e) {
            System.out.println("Error on accepting connection: " + e.getMessage());
        }
    }
}
